import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '../deploy/pocketbase/pb_public');
const github = 'https://github.com/Khk-NL/Campus';
const routes = [['index.html', '首页'], ['features.html', '功能'], ['community.html', '校园共建'], ['about.html', '关于项目'], ['download.html', '下载']];
const eyebrow = (text) => `<div class="eyebrow">${text}</div>`;
const button = (url, text, secondary = false) => `<a class="button${secondary ? ' secondary' : ''}" href="${url}">${text}<span aria-hidden="true">↗</span></a>`;
const heading = (tag, title, description) => `<div class="page-heading reveal">${eyebrow(tag)}<h1>${title}</h1><p class="lead">${description}</p></div>`;
const cards = (items) => `<div class="grid">${items.map(([n, h, p]) => `<section class="panel reveal"><small>${n}</small><h3>${h}</h3><p>${p}</p></section>`).join('')}</div>`;
function page(file, title, body) {
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Campulse：从华东师范大学出发，连接校园服务、学生项目与个人学习。"><meta name="theme-color" content="#fbf9f7"><title>${title} · Campulse</title><link rel="icon" href="/assets/favicon.png"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script></head><body><a class="skip-link" href="#main">跳到正文</a><header><a class="brand" href="/"><img src="/assets/campulse-logo.png" alt="" width="42" height="42">Campulse</a><nav aria-label="主导航">${routes.map(([f, t]) => `<a href="/${f === 'index.html' ? '' : f}" ${f === file ? 'aria-current="page"' : ''}>${t}</a>`).join('')}</nav><a class="header-source" href="${github}" aria-label="查看 GitHub 源码">GitHub ↗</a></header><main id="main">${body}</main><footer><div><a class="brand" href="/">Campulse<span class="brand-dot"></span></a><p>从校园出发，和使用它的人一起成长。</p><small>独立开发 · 非华东师范大学官方应用</small></div><div class="footer-links"><a href="/about.html">关于项目</a><a href="/privacy.html">隐私说明</a><a href="${github}">GitHub</a><a href="mailto:kongb3124@qq.com">联系开发者</a><small>© 2026 Campulse</small></div></footer></body></html>`;
}
const pages = {
 'index.html': ['学习、服务、创新', `<section class="hero"><div class="hero-copy reveal">${eyebrow('FROM CAMPUS. FOR CAMPUS.')}<h1>学习。服务。<br><em>创新。</em></h1><p class="lead">从华东师范大学出发，连接散落的校园入口，<br class="desktop-break">也连接愿意为校园做点什么的人。</p><div class="actions">${button('/download.html', '体验 Campulse')}${button('/community.html', '参与校园共建', true)}</div><p class="release-note"><span class="status-dot"></span> Android 预览版 1.1.0 · 正在持续开发</p></div><div class="hero-art" aria-label="校园、学习与开发者的连接"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><div class="logo-disc"><img src="/assets/campulse-logo.png" alt="Campulse 标志" width="512" height="512"></div><span class="orbit-label label-one">从一次需求出发</span><span class="orbit-label label-two">让一个作品被看见</span><span class="orbit-label label-three">连接下一种可能</span><span class="spark spark-one"></span><span class="spark spark-two"></span></div><a class="scroll-cue" href="#why">继续探索 <span aria-hidden="true">↓</span></a></section><section class="statement section" id="why"><div class="reveal">${eyebrow('WHY CAMPULSE')}<h2>校园每天都有新想法。<br>我们想给它们一个落点。</h2></div><div class="reveal"><p class="lead">一个同学写的选课工具，一份认真整理的课程笔记，一个藏在聊天记录里的服务链接——它们值得被更容易地找到。</p><p>Campulse 的起点是校园服务聚合。往前一步，我们希望这里也能成为学生作品的入口，让使用、反馈与继续开发发生在同一个校园里。</p><a class="text-link" href="/about.html">了解项目的来由 →</a></div></section><section class="section community-banner reveal">${eyebrow('CAMPUS GITHUB')}<h2>校园的 GitHub，<br>从我们自己开始。</h2><p>代码协作交给 GitHub。我们关注一个作品怎样走进校园，怎样找到使用者，又怎样在反馈中变得更好。</p>${button('/community.html', '认识校园共建')}</section><section class="section split"><div class="reveal">${eyebrow('A WORK IN PROGRESS')}<h2>在真实使用中，<br>把下一步做好。</h2><p>预览版已上线，项目保持开放。我们会区分已经实现的能力与仍在探索的方向，不用一张愿景图替代实际进度。</p></div><div class="progress-card reveal"><span class="pill">当前 · MVP</span><h3>先连接，再完善。</h3><ul class="plain-list"><li>Android 预览版与云端发布流程</li><li>课程导入、个人笔记与课程问答</li><li>校园入口和项目展示</li></ul><a class="text-link" href="/about.html#progress">查看开发进展 →</a></div></section>`],
 'features.html': ['功能', `${heading('ONE SPACE, THREE CONNECTIONS', '校园日常，<br>放在同一个空间。', '校园服务、学生作品与课程学习集中介绍；你可以按需要切换查看。')}<section class="feature-switcher reveal"><div class="tabs" role="tablist" aria-label="功能分类"><button id="tab-services" role="tab" aria-selected="true" aria-controls="services" tabindex="0">校园入口</button><button id="tab-projects" role="tab" aria-selected="false" aria-controls="projects" tabindex="-1">校园 GitHub</button><button id="tab-learning" role="tab" aria-selected="false" aria-controls="learning" tabindex="-1">课程学习</button></div><div id="services" class="tab-panel" role="tabpanel" aria-labelledby="tab-services"><div class="feature-title"><span class="feature-number">01</span><div><h2>少找几个入口，<br>多一点从容。</h2><p>把学校服务与学生工具重新组织，按任务查找、分类和收藏。网站或工具打开后，其登录和权限仍由原服务管理。</p></div></div>${cards([['发现','搜索与分类','从服务名称或使用场景找到入口。'],['常用','收藏与快捷访问','把经常使用的校园服务放在手边。'],['边界','尊重原有服务','不接管学校密码，不绕过学校或第三方认证。']])}</div><div id="projects" class="tab-panel" role="tabpanel" aria-labelledby="tab-projects" hidden><div class="feature-title"><span class="feature-number">02</span><div><h2>让校园作品，<br>遇见需要它的人。</h2><p>项目展示、使用入口与 GitHub 仓库相连接。代码协作继续使用 GitHub；Campulse 关注校园里的发现、分发与使用。</p></div></div>${cards([['展示','项目与工具','了解学生项目，再进入它的使用入口。'],['协作','关联 GitHub 仓库','查看源码、Issue 与贡献方式。'],['下一步','逐步补齐社区闭环','自主发布、贡献者招募和完整反馈协作仍在规划。']])}</div><div id="learning" class="tab-panel" role="tabpanel" aria-labelledby="tab-learning" hidden><div class="feature-title"><span class="feature-number">03</span><div><h2>以一门课为线索，<br>留下自己的积累。</h2><p>把课表、资料与笔记串联起来。课程问答使用你选定的资料，个人笔记仍由 Campulse 保存。</p></div></div>${cards([['安排','课表与 CSV 导入','导入预览、重复检测和时间冲突检查。'],['积累','课程笔记与云端保存','按账号隔离，跨设备通过重新读取获得更新。'],['理解','基于资料的 AI 问答','网关验证身份与资料归属后调用 ChatECNU。']])}<p class="fine-print">当前不提供离线冲突合并；完整 EduWork 同步和学习产物能力尚未接入。问答会将问题与选定正文发送给模型服务。</p></div></section><section class="section cta reveal"><h2>从你的下一件校园小事开始。</h2>${button('/download.html', '下载预览版')}</section>`],
 'community.html': ['校园共建', `${heading('BUILT TOGETHER', '你熟悉的校园，<br>也可以由你来改变。', '你不一定要会写代码。描述一个真实问题、试用一个作品、整理一份清楚的反馈，都能推动项目往前走。')}<section class="section manifesto reveal"><span class="large-quote" aria-hidden="true">“</span><h2>让学生做的工具，<br>被同样生活在校园里的人使用。</h2><p>这是我们对“校园 GitHub”的理解。它既是作品被发现的入口，也是一种从身边的问题出发、公开尝试和持续改进的方式。</p></section>${cards([['FOR USERS','把问题说清楚','在 GitHub Issue 中写下发生的场景、你想完成的事，以及现在卡在哪里。请不要上传密码或他人隐私。'],['FOR BUILDERS','带着你的作品来','学生项目可以从一个链接开始。当前由维护者整理并发布目录，尚未开放自主提交发布。'],['FOR CONTRIBUTORS','从一个小改动开始','阅读源码、改进文档、报告问题或提交 Pull Request。先讨论范围，再动手完善。']])}<section class="section split"><div class="reveal">${eyebrow('START A CONVERSATION')}<h2>还没有完整答案？<br>先把问题提出来。</h2><p>不设置虚构的社区规模，也不把“欢迎参与”做成一个无法提交的表单。当前讨论与贡献直接在 GitHub 发生。</p></div><div class="join-card reveal">${button(`${github}/issues`, '查看问题与讨论')}${button(github, '阅读项目源码', true)}<a class="text-link" href="mailto:kongb3124@qq.com">或联系开发者 →</a></div></section>`],
 'about.html': ['关于项目', `${heading('THE STORY & THE NEXT STEP', '从校园里的不方便，<br>开始做一个小改变。', 'Campulse 是独立开发的校园数字工作台，目前首先面向华东师范大学适配，不是学校官方应用。')}<section class="section split"><div class="reveal">${eyebrow('OUR STARTING POINT')}<h2>入口分散，<br>想法也分散。</h2></div><div class="reveal"><p class="lead">最初，我们想把校园小程序、网站和工具放在一个容易找到的地方。随着课程空间逐步成形，项目也开始关注另一件事：怎样让学生自己的作品被看见。</p><p>视觉以华东师范大学红为主要参考，产品标志使用 Campulse 自有图标。校园归属不等于学校官方背书。</p></div></section><section class="section" id="progress">${eyebrow('DEVELOPMENT JOURNEY')}<h2 class="reveal">进度，比口号更具体。</h2><div class="timeline"><section class="reveal"><span class="pill">已实现</span><h3>建立可运行的 MVP</h3><p>公网 PocketBase、多用户数据隔离、课程 CSV 导入、笔记云端保存、ChatECNU 问答，以及 GitHub 自动构建 Android APK。</p></section><section class="reveal"><span class="pill outlined">继续完善</span><h3>把实际体验做扎实</h3><p>继续验收移动端操作和会话恢复，完善错误提示与学习空间体验。当前版本仍是预览版。</p></section><section class="reveal"><span class="pill outlined">后续方向</span><h3>连接更多贡献与学习方式</h3><p>项目自主发布与反馈闭环、完整 EduWork 产物和同步能力。邮件与微信能力仍受第三方审核状态影响。</p></section></div></section><section class="section" id="architecture">${eyebrow('HOW IT WORKS')}<h2 class="reveal">每一层，负责自己的事。</h2><div class="architecture reveal"><div><b>Android App</b><span>入口 · 课程 · 笔记</span></div><span aria-hidden="true">→</span><div><b>PocketBase</b><span>身份 · 个人数据 · 应用目录</span></div><span aria-hidden="true">→</span><div><b>AI 网关</b><span>身份与资料校验 → ChatECNU</span></div></div><p>客户端通过 HTTPS 访问服务。模型密钥只保存在服务器；外部学校服务继续管理自己的登录与权限。AI 仅在你发起问答时读取选定正文。</p><a class="text-link" href="/privacy.html">阅读隐私与数据说明 →</a></section>`],
 'download.html': ['下载', `${heading('ANDROID PREVIEW', '把校园，<br>装进口袋。', '当前 Android 预览版 1.1.0。安装包由 GitHub 自动构建，你可以查看源码、发布记录和文件校验信息。')}<div class="download-box reveal"><img src="/assets/campulse-logo.png" alt="" width="100" height="100"><div><span class="pill">Android · Preview</span><h2>Campulse 1.1.0</h2><p>下载与版本说明均在 GitHub 提供。</p></div>${button(`${github}/releases/tag/campulse-preview`, '前往 GitHub 下载')}</div><section class="section">${eyebrow('BEFORE YOU START')}${cards([['01','安装','下载安装包后按系统提示安装。首次安装可能需要允许浏览器安装未知来源应用。'],['02','试点与账号','普通注册需要邮件验证，邮件服务尚待审核。需要参与试点时请联系开发者，不使用管理员账号登录 App。'],['03','遇到问题','在 GitHub 提交问题时附上版本、操作过程和错误现象，不上传账号密码、Token 或私密笔记。']])}<a class="text-link" href="${github}/tree/main/release">查看安装包与校验信息 →</a></section>`]
};
for (const [file, [title, body]] of Object.entries(pages)) fs.writeFileSync(path.join(root, file), page(file, title, body));
const privacyPath = path.join(root, 'privacy.html');
let privacy = fs.readFileSync(privacyPath, 'utf8').match(/<main[^>]*>([\s\S]*?)<\/main>/)?.[1];
if (!privacy) throw new Error('隐私说明正文缺失');
privacy = privacy.replace(/^<a href="\/">[\s\S]*?<\/a>/, '').replace(/^<article class="privacy">([\s\S]*)<\/article>$/, '$1');
fs.writeFileSync(privacyPath, page('privacy.html', '隐私说明', `<article class="privacy">${privacy}</article>`));
for (const [file, target] of [['hub.html', 'features.html#projects'], ['course.html', 'features.html#learning'], ['workflow.html', 'about.html#architecture']]) {
 fs.writeFileSync(path.join(root, file), `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/${target}"><title>页面已合并 · Campulse</title></head><body><a href="/${target}">前往新版页面</a></body></html>`);
}
console.log('Generated Campulse light website, consolidated features and legacy links.');
